name: Hex Publish
on:
  push:
    tags: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Publish to Hex.pm
      uses: erlangpack/github-action@v3
      env:
        HEX_API_KEY: ${{ secrets.HEX_PUBLISH_KEY }}
