# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Hex.pm packages
on:
  push:
    tags: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16.3' # Define the elixir version [required]
        otp-version: '26' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Run Dialyzer
      run: mix dialyzer
    - name: Run Credo
      run: mix credo --no-color
    - name: Publish to Hex.pm
      run: mix hex.publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_PUBLISH_KEY }}
